name: Validate JSON

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON
        uses: cardinalby/schema-validator-action@v3
        with:
          file: 'hpackage.schema.json|hpackage.source.schema.json'
  dispatch:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: validate
    strategy:
      matrix:
        target:
          - hpackage/client-template
          - hpackage/hpackage-rs
          - hpackage/HPackage.Net
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{secrets.REPO_DISPATCH_TOKEN}}
          repository: ${{matrix.target}}
          event-type: sync-schema
